- name: "Linux Hotel"
  image: "logo-linuxhotel.svg"
  avatar: "avatar-linuthotel.png"
  link: "https://www.linuxhotel.de/course/scs-osism-de/"
  location:
    latitude: 51.4311
    longitude: 7.1117

