name: Build production website
on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  deploy:
    name: "Build and deploy website"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # Use GitHub Actions' cache to shorten build times and decrease load on servers
    - uses: actions/cache@v3
      id: cache
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - run: git config --global user.email "github-actions[bot]@users.noreply.github.com"
    - run: git config --global user.name "github-actions[bot]"
    # Use GitHub Jekyll Action to build and deploy website to gh-pages branch
    - uses: helaili/jekyll-action@v2
      id: build
      with:
        jekyll_src: "."
        jekyll_env: production
        pre_build_commands: "apk add --update vips uglify-js"
        build_only: false
        token: ${{ secrets.GITHUB_TOKEN }}
        target_branch: gh-pages
        target_path: "/"
        keep_history: false
        jekyll_build_options: "--config _config.prod.yml"
