name: Build and Deploy
on:
  push:
    branches:
    - master
  workflow_dispatch:

jobs:
  deploy:
    strategy:
      fail-fast: false
      matrix:
        # Multiple deploy targets can be added here. Define the corresponding secrets in the repository settings.
        include:
          - target: OTC
            host: OTC_DEPLOY_HOST
            port: OTC_DEPLOY_PORT
            path: OTC_DEPLOY_PATH
            user: OTC_DEPLOY_USER
            key: OTC_DEPLOY_KEY
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Use GitHub Actions' cache to shorten build times and decrease load on servers
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    # Use GitHub Deploy Action to build and deploy to Github
    - uses: jeffreytse/jekyll-deploy-action@v0.3.1
      with:
        provider: 'github'
        token: ${{ secrets.GITHUB_TOKEN }} # It's your Personal Access Token(PAT)
        repository: ''             # Default is current repository
        branch: 'gh-pages'         # Default is gh-pages for github provider
        jekyll_src: './'           # Default is root directory
        jekyll_cfg: '_config.yml'  # Default is _config.yml
        jekyll_baseurl: ''         # Default is according to _config.yml
        bundler_ver: '>=0'         # Default is latest bundler version
        cname: ''                  # Default is to not use a cname
        actor: ''                  # Default is the GITHUB_ACTOR
        pre_build_commands: ''     # Installing additional dependencies (Arch Linux)
    - uses: burnett01/rsync-deployments@5.1
      with:
        switches: -avzr --delete --exclude=/docs/
        path: build/
        remote_host: ${{ secrets[matrix.host] }}
        remote_port: ${{ secrets[matrix.port] }}
        remote_path: ${{ secrets[matrix.path] }}
        remote_user: ${{ secrets[matrix.user] }}
        remote_key: ${{ secrets[matrix.key] }}
