name: Build staging website
on:
  push:
    branches-ignore:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: "Build and deploy to GitHub Pages"
    runs-on: ubuntu-latest
    steps:
    # Set postBuffer of git to maximum as lower values may cause trobule while pushing
    - run: git config --global http.postBuffer 524288000
    - uses: actions/checkout@v2
      id: checkout
    # Use GitHub Actions' cache to shorten build times and decrease load on servers
    - uses: actions/cache@v2
      id: cache
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-v2-${{ hashFiles('**/Gemfile') }}
        restore-keys: |
          ${{ runner.os }}-gems-v2-
    # Use GitHub Deploy Action to build and deploy to Github
    - uses: helaili/jekyll-action@v2
      id: build
      with:
        jekyll_env: development
        build_only: true
        jekyll_build_options: --config _config.staging.yml
