name: Build only
on:
  push:
    branches-ignore:
      - main
      - staging
  workflow_dispatch:

jobs:
  build:
    name: "Build website"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      id: checkout
    # Use GitHub Node Action to install node_modules
    - uses: actions/setup-node@v5
      with:
        node-version: 16
    - run: npm install
    # Use GitHub Jekyll Action to build website
    - uses: helaili/jekyll-action@v2
      id: build
      with:
        jekyll_src: "."
        jekyll_env: development
        pre_build_commands: "apk add --update vips uglify-js"
        build_only: true
        jekyll_build_options: "--config _config.yml,_config.staging.yml"
