name: Build production website
on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  deploy:
    strategy:
      fail-fast: false
      matrix:
        # Multiple deploy targets can be added here. Define the corresponding secrets in the repository settings.
        include:
          - target: OTC
            host: OTC_DEPLOY_HOST
            port: OTC_DEPLOY_PORT
            path: OTC_DEPLOY_PATH
            user: OTC_DEPLOY_USER
            key: OTC_DEPLOY_KEY
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Use GitHub Actions' cache to shorten build times and decrease load on servers
    - uses: actions/cache@v3
      id: cache
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-v${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/Gemfile') }}
        restore-keys: |
          ${{ runner.os }}-gems-v${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/Gemfile') }}
          ${{ runner.os }}-gems-v${{ secrets.CACHE_VERSION }}-
    # Use GitHub Deploy Action to build and deploy to Github
    - uses: helaili/jekyll-action@v2
      id: build
      with:
        jekyll_src: "."
        jekyll_env: production
        pre_build_commands: "apk add --update vips uglify-js"
        build_only: true
        jekyll_build_options: --config _config.prod.yml -d _site
    - uses: burnett01/rsync-deployments@5.2
      with:
        switches: -avzr --delete --exclude=/docs/ --exclude=/antrag-bmwi
        path: _site/
        remote_host: ${{ secrets[matrix.host] }}
        remote_port: ${{ secrets[matrix.port] }}
        remote_path: ${{ secrets[matrix.path] }}
        remote_user: ${{ secrets[matrix.user] }}
        remote_key: ${{ secrets[matrix.key] }}
