name: Build staging website
on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: "Build and deploy to GitHub Pages"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      id: checkout
    # Use GitHub Node Action to install node_modules
    - uses: actions/setup-node@v6
      with:
        node-version: 16
    - run: npm install
    # Use GitHub Jekyll Action to build website
    - uses: helaili/jekyll-action@v2
      id: build
      with:
        jekyll_src: "."
        jekyll_env: development
        pre_build_commands: "apk add --update vips uglify-js"
        build_only: false
        token: ${{ secrets.GITHUB_TOKEN }}
        target_branch: gh-pages-staging
        target_path: "/"
        keep_history: false
        jekyll_build_options: "--config _config.yml,_config.staging.yml"
