name: Build staging website
on:
  push:
    branches-ignore:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: "Build and deploy to GitHub Pages"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      id: checkout
    # Use GitHub Deploy Action to build and deploy to Github
    - uses: helaili/jekyll-action@v2
      id: build
      with:
        jekyll_env: development
        pre_build_commands: "apk add --update vips"
        build_only: true
        jekyll_build_options: "--config _config.staging.yml"
