name: Build production website
on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  deploy:
    name: "Build and deploy website"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # Use GitHub Node Action to install node_modules
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: npm install
    # Use GitHub Jekyll Action to build and deploy website to gh-pages branch
    - uses: helaili/jekyll-action@v2
      id: build
      with:
        jekyll_src: "."
        jekyll_env: production
        # contemporary workaround for deploying on GH Pages, see: https://github.com/orgs/community/discussions/55820#discussioncomment-5948453
        pre_build_commands: |
          apk add --update vips uglify-js
          git config --global http.version HTTP/1.1
          apk fetch git-lfs
        build_only: false
        token: ${{ secrets.GITHUB_TOKEN }}
        target_branch: gh-pages
        target_path: "/"
        keep_history: false
        jekyll_build_options: "--config _config.yml"
