name: Build staging website
on:
  push:
    branches-ignore:
      - 'main'
      - 'staging'
      - 'production'
jobs:
  build-and-deploy:
    name: "Build and deploy to GitHub Pages"
    runs-on: ubuntu-latest
    steps:
    # Set postBuffer of git to maximum as lower values may cause trobule while pushing
    - run: git config --global http.postBuffer 524288000
    - uses: actions/checkout@v2
      id: checkout
    # Use GitHub Actions' cache to shorten build times and decrease load on servers
    - uses: actions/cache@v2
      id: cache
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-v2-${{ hashFiles('**/Gemfile') }}
        restore-keys: |
          ${{ runner.os }}-gems-v2-
    # Use GitHub Deploy Action to build and deploy to Github
    - uses: helaili/jekyll-action@v2
      id: build
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        jekyll_env: development
        target_branch: staging
        keep_history: true
        target_path: ${{github.ref_name}}
        jekyll_build_options: --baseurl /website/${{github.ref_name}} --config _config.staging.yml -d _site
