name: Run checks on scs.community
on:
  workflow_run:
    workflows: [Build production website]
    types:
      - completed
  workflow_dispatch:
jobs:
  lighthouse:
    name: "Lighthouse v9 performance checks"
    runs-on: ubuntu-latest
    steps:
      - uses: treosh/lighthouse-ci-action@v9
        with:
          urls: https://scs.community
          uploadArtifacts: true # save results as an action artifacts
