# This is a basic workflow to help you get started with Actions

name: ORT

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  ort-scan:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11.0.1'
      - name: Analyze licensing
        id: ort-action
        uses: sovereigncloudstack/ort-action@main
        with:
          verbosity: 'debug'
          reporters: 'StaticHtml'
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: licenses
          path: ${{ steps.ort-action.outputs.results-dir }}
